name: Auto Multiple Commits

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the job every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Use the latest version of actions/checkout

    - name: Set up Git
      run: |
        git config --global user.email "mwendamutai@gmail.com"  # Make sure email is correct
        git config --global user.name "nashon11"  # Set your GitHub username

    - name: Make 20 commits
      run: |
        for i in {1..20}; do
          echo "Last updated: $(date) - Commit #$i" >> README.md  # Force a change with a unique message
          git add README.md
          git commit -m "Auto commit #$i on $(date)" || echo "No changes to commit"
        done

    - name: Push Changes
      run: git push

# Adding a comment to force a change
# This is my auto-commit workflow

